-- Script SQL para eliminar datos registrados o fechados antes de Junio (2026-06-01)
-- IMPORTANTE: Ejecutar dentro de una transacción para mantener la integridad referencial.

BEGIN;

-- 1. Asistencias
DELETE FROM ASISTENCIA 
WHERE FECHA < '2026-06-01' 
   OR ID_SESION IN (SELECT ID_SESION FROM SESION_CLASE WHERE FECHA < '2026-06-01');

-- 2. Sesiones de clase
DELETE FROM SESION_CLASE WHERE FECHA < '2026-06-01';

-- 3. Calificaciones y Notas
DELETE FROM NOTA 
WHERE FECHA_REGISTRO < '2026-06-01' 
   OR ID_EVALUACION IN (SELECT ID_EVALUACION FROM EVALUACION WHERE FECHA_EVALUACION < '2026-06-01');

-- 4. Entregas de Evaluaciones
DELETE FROM ENTREGA_EVALUACION 
WHERE FECHA_ENTREGA < '2026-06-01' 
   OR ID_EVALUACION IN (SELECT ID_EVALUACION FROM EVALUACION WHERE FECHA_EVALUACION < '2026-06-01');

-- 5. Evaluaciones
DELETE FROM EVALUACION WHERE FECHA_EVALUACION < '2026-06-01';

-- 6. Recursos Publicados
DELETE FROM RECURSOS WHERE FECHA_PUBLICACION < '2026-06-01';

-- 7. Eventos de Calendario Académico
DELETE FROM CALENDARIO_ACADEMICO WHERE FECHA_INICIO < '2026-06-01';

-- 8. Participantes de Asesorías
DELETE FROM PARTICIPANTE_ASESORIA 
WHERE ID_ASESORIA IN (SELECT ID_ASESORIA FROM ASESORIA WHERE FECHA_HORA < '2026-06-01');

-- 9. Asesorías
DELETE FROM ASESORIA WHERE FECHA_HORA < '2026-06-01';

-- 10. Respuestas de Foros
DELETE FROM RESPUESTA_FORO 
WHERE FECHA_RESPUESTA < '2026-06-01' 
   OR ID_TEMA IN (SELECT ID_TEMA FROM TEMA_FORO WHERE FECHA_CREACION < '2026-06-01' 
                  OR ID_FORO IN (SELECT ID_FORO FROM FORO WHERE FECHA_CREACION < '2026-06-01'));

-- 11. Temas de Foros
DELETE FROM TEMA_FORO 
WHERE FECHA_CREACION < '2026-06-01' 
   OR ID_FORO IN (SELECT ID_FORO FROM FORO WHERE FECHA_CREACION < '2026-06-01');

-- 12. Foros
DELETE FROM FORO WHERE FECHA_CREACION < '2026-06-01';

-- 13. Anuncios
DELETE FROM ANUNCIO WHERE FECHA_PUBLICACION < '2026-06-01';

-- 14. Incidencias de Soporte
DELETE FROM INCIDENCIA_SOPORTE WHERE FECHA_CREACION < '2026-06-01';

-- 15. Notificaciones
DELETE FROM NOTIFICACION WHERE FECHA_CREACION < '2026-06-01';

-- 16. Integrantes de Grupos
DELETE FROM GRUPO_ESTUDIANTE 
WHERE ID_GRUPO IN (SELECT ID_GRUPO FROM GRUPO WHERE FECHA_CREACION < '2026-06-01');

-- 17. Grupos de Trabajo
DELETE FROM GRUPO WHERE FECHA_CREACION < '2026-06-01';

COMMIT;
