-- =========================================================================================
-- SCRIPT DE CREACIÓN DE BASE DE DATOS: VIRTUCLASS
-- Motor: PostgreSQL
-- Descripción: Script completo para la creación de las 28 tablas, claves primarias, 
-- claves foráneas, restricciones (CHECK) y relaciones del sistema VirtuClass.
-- =========================================================================================

-- 1. ELIMINACIÓN DE TABLAS SI EXISTEN (En orden inverso a las dependencias)
DROP TABLE IF EXISTS BITACORA_ADMIN CASCADE;
DROP TABLE IF EXISTS NOTIFICACION CASCADE;
DROP TABLE IF EXISTS INCIDENCIA_SOPORTE CASCADE;
DROP TABLE IF EXISTS CONFIGURACION_GLOBAL CASCADE;
DROP TABLE IF EXISTS ANUNCIO CASCADE;
DROP TABLE IF EXISTS RESPUESTA_FORO CASCADE;
DROP TABLE IF EXISTS TEMA_FORO CASCADE;
DROP TABLE IF EXISTS FORO CASCADE;
DROP TABLE IF EXISTS PARTICIPANTE_ASESORIA CASCADE;
DROP TABLE IF EXISTS ASESORIA CASCADE;
DROP TABLE IF EXISTS ASISTENCIA CASCADE;
DROP TABLE IF EXISTS SESION_CLASE CASCADE;
DROP TABLE IF EXISTS CALENDARIO_ACADEMICO CASCADE;
DROP TABLE IF EXISTS GRUPO_ESTUDIANTE CASCADE;
DROP TABLE IF EXISTS GRUPO CASCADE;
DROP TABLE IF EXISTS NOTA CASCADE;
DROP TABLE IF EXISTS ENTREGA_EVALUACION CASCADE;
DROP TABLE IF EXISTS EVALUACION CASCADE;
DROP TABLE IF EXISTS RECURSOS CASCADE;
DROP TABLE IF EXISTS MODULO_CLASE CASCADE;
DROP TABLE IF EXISTS UNIDAD CASCADE;
DROP TABLE IF EXISTS MATRICULA CASCADE;
DROP TABLE IF EXISTS CLASE_DOCENTE CASCADE;
DROP TABLE IF EXISTS CLASE CASCADE;
DROP TABLE IF EXISTS CURSO CASCADE;
DROP TABLE IF EXISTS USUARIO_ROL CASCADE;
DROP TABLE IF EXISTS ROL CASCADE;
DROP TABLE IF EXISTS USUARIO CASCADE;

-- =========================================================================================
-- 2. CREACIÓN DE TABLAS PRINCIPALES (Sin dependencias foráneas)
-- =========================================================================================

CREATE TABLE USUARIO (
    ID_USUARIO SERIAL PRIMARY KEY,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    CORREO VARCHAR(100) UNIQUE NOT NULL,
    CONTRASENA VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(20),
    ESTADO VARCHAR(20) DEFAULT 'Activo' CHECK (ESTADO IN ('Activo', 'Inactivo', 'PENDIENTE')),
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ROL (
    ID_ROL SERIAL PRIMARY KEY,
    NOMBRE_ROL VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE CURSO (
    ID_CURSO SERIAL PRIMARY KEY,
    CODIGO VARCHAR(50) UNIQUE NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    CREDITOS INT NOT NULL DEFAULT 0,
    ESTADO VARCHAR(20) DEFAULT 'Activo'
);

CREATE TABLE CONFIGURACION_GLOBAL (
    CLAVE VARCHAR(50) PRIMARY KEY,
    VALOR VARCHAR(255) NOT NULL
);

-- =========================================================================================
-- 3. CREACIÓN DE TABLAS INTERMEDIAS Y ESTRUCTURALES
-- =========================================================================================

CREATE TABLE USUARIO_ROL (
    ID_USUARIO INT REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    ID_ROL INT REFERENCES ROL(ID_ROL) ON DELETE CASCADE,
    PRIMARY KEY (ID_USUARIO, ID_ROL)
);

CREATE TABLE CLASE (
    ID_CLASE SERIAL PRIMARY KEY,
    ID_CURSO INT REFERENCES CURSO(ID_CURSO) ON DELETE CASCADE,
    NOMBRE_CLASE VARCHAR(100) NOT NULL,
    PERIODO VARCHAR(20) NOT NULL,
    CICLO VARCHAR(20),
    SECCION VARCHAR(20),
    AULA VARCHAR(20),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ENLACE_VIDEO VARCHAR(255),
    ENLACE_WHATSAPP VARCHAR(255),
    DRIVE_FOLDER_ID VARCHAR(255),
    ESTADO VARCHAR(20) DEFAULT 'Activo'
);

CREATE TABLE CLASE_DOCENTE (
    ID_CLASE INT REFERENCES CLASE(ID_CLASE) ON DELETE CASCADE,
    ID_USUARIO INT REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    PRIMARY KEY (ID_CLASE, ID_USUARIO)
);

CREATE TABLE MATRICULA (
    ID_MATRICULA SERIAL PRIMARY KEY,
    ID_CLASE INT REFERENCES CLASE(ID_CLASE) ON DELETE CASCADE,
    ID_USUARIO INT REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    FECHA_MATRICULA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO_MATRICULA VARCHAR(20) DEFAULT 'ACTIVO' CHECK (ESTADO_MATRICULA IN ('ACTIVO', 'RETIRADO', 'FINALIZADO'))
);

-- =========================================================================================
-- 4. ESTRUCTURA MODULAR (Unidades, Semanas y Contenido)
-- =========================================================================================

CREATE TABLE UNIDAD (
    ID_UNIDAD SERIAL PRIMARY KEY,
    ID_CLASE INT REFERENCES CLASE(ID_CLASE) ON DELETE CASCADE,
    TITULO VARCHAR(100) NOT NULL,
    NUMERO INT DEFAULT 1
);

CREATE TABLE MODULO_CLASE (
    ID_MODULO SERIAL PRIMARY KEY,
    ID_CLASE INT REFERENCES CLASE(ID_CLASE) ON DELETE CASCADE,
    ID_UNIDAD INT REFERENCES UNIDAD(ID_UNIDAD) ON DELETE CASCADE,
    TITULO VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    ORDEN INT DEFAULT 0
);

CREATE TABLE RECURSOS (
    ID_RECURSO SERIAL PRIMARY KEY,
    ID_CLASE INT REFERENCES CLASE(ID_CLASE) ON DELETE CASCADE,
    ID_MODULO INT REFERENCES MODULO_CLASE(ID_MODULO) ON DELETE SET NULL,
    TITULO VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    TIPO_RECURSO VARCHAR(20) CHECK (TIPO_RECURSO IN ('pdf', 'video', 'documento', 'link', 'imagen', 'otro')),
    URL_ARCHIVO VARCHAR(255),
    FECHA_PUBLICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DRIVE_FILE_ID VARCHAR(255),
    DRIVE_URL VARCHAR(255)
);

-- =========================================================================================
-- 5. GESTIÓN ACADÉMICA (Evaluaciones, Notas, Asistencia y Calendario)
-- =========================================================================================

CREATE TABLE EVALUACION (
    ID_EVALUACION SERIAL PRIMARY KEY,
    ID_CLASE INT REFERENCES CLASE(ID_CLASE) ON DELETE CASCADE,
    ID_MODULO INT REFERENCES MODULO_CLASE(ID_MODULO) ON DELETE SET NULL,
    NOMBRE_EVA VARCHAR(100) NOT NULL,
    PORCENTAJE DECIMAL(5,2) NOT NULL,
    FECHA_EVALUACION DATE,
    ARCHIVO_URL VARCHAR(255),
    DRIVE_FILE_ID VARCHAR(255),
    DRIVE_URL VARCHAR(255)
);

CREATE TABLE ENTREGA_EVALUACION (
    ID_ENTREGA SERIAL PRIMARY KEY,
    ID_EVALUACION INT REFERENCES EVALUACION(ID_EVALUACION) ON DELETE CASCADE,
    ID_USUARIO INT REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    ARCHIVO_URL VARCHAR(255),
    FECHA_ENTREGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DRIVE_FILE_ID VARCHAR(255),
    DRIVE_URL VARCHAR(255)
);

CREATE TABLE NOTA (
    ID_NOTA SERIAL PRIMARY KEY,
    ID_EVALUACION INT REFERENCES EVALUACION(ID_EVALUACION) ON DELETE CASCADE,
    ID_USUARIO INT REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    CALIFICACION DECIMAL(5,2),
    COMENTARIO TEXT,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SESION_CLASE (
    ID_SESION SERIAL PRIMARY KEY,
    ID_CLASE INT REFERENCES CLASE(ID_CLASE) ON DELETE CASCADE,
    ID_MODULO INT REFERENCES MODULO_CLASE(ID_MODULO) ON DELETE SET NULL,
    TEMA VARCHAR(150),
    DESCRIPCION TEXT,
    FECHA DATE,
    HORA_INICIO TIME,
    HORA_FIN TIME
);

CREATE TABLE ASISTENCIA (
    ID_ASISTENCIA SERIAL PRIMARY KEY,
    ID_SESION INT REFERENCES SESION_CLASE(ID_SESION) ON DELETE CASCADE,
    ID_MODULO INT REFERENCES MODULO_CLASE(ID_MODULO) ON DELETE SET NULL,
    ID_USUARIO INT REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    FECHA DATE,
    ESTADO VARCHAR(20) CHECK (ESTADO IN ('presente', 'ausente', 'tardanza', 'sin marcar'))
);

CREATE TABLE CALENDARIO_ACADEMICO (
    ID_EVENTO SERIAL PRIMARY KEY,
    ID_CLASE INT REFERENCES CLASE(ID_CLASE) ON DELETE CASCADE,
    TITULO_EVENTO VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    FECHA_INICIO TIMESTAMP NOT NULL,
    FECHA_FIN TIMESTAMP,
    TIPO_EVENTO VARCHAR(20) CHECK (TIPO_EVENTO IN ('examen', 'feriado', 'entrega', 'reunion', 'otro')),
    ID_EVALUACION INT REFERENCES EVALUACION(ID_EVALUACION) ON DELETE CASCADE
);

-- =========================================================================================
-- 6. GESTIÓN DE GRUPOS Y ASESORÍAS
-- =========================================================================================

CREATE TABLE GRUPO (
    ID_GRUPO SERIAL PRIMARY KEY,
    ID_CLASE INT REFERENCES CLASE(ID_CLASE) ON DELETE CASCADE,
    NOMBRE_GRUPO VARCHAR(100) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE GRUPO_ESTUDIANTE (
    ID_GRUPO INT REFERENCES GRUPO(ID_GRUPO) ON DELETE CASCADE,
    ID_USUARIO INT REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    PRIMARY KEY (ID_GRUPO, ID_USUARIO)
);

CREATE TABLE ASESORIA (
    ID_ASESORIA SERIAL PRIMARY KEY,
    ID_DOCENTE INT REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    ID_SOLICITANTE INT REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    ID_GRUPO INT REFERENCES GRUPO(ID_GRUPO) ON DELETE SET NULL,
    MOTIVO VARCHAR(150) NOT NULL,
    DESCRIPCION TEXT,
    FECHA_HORA TIMESTAMP,
    ENLACE_REUNION VARCHAR(255),
    ESTADO VARCHAR(20) DEFAULT 'pendiente' CHECK (ESTADO IN ('pendiente', 'confirmada', 'rechazada'))
);

CREATE TABLE PARTICIPANTE_ASESORIA (
    ID_ASESORIA INT REFERENCES ASESORIA(ID_ASESORIA) ON DELETE CASCADE,
    ID_USUARIO INT REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    PRIMARY KEY (ID_ASESORIA, ID_USUARIO)
);

-- =========================================================================================
-- 7. FOROS DE COMUNICACIÓN
-- =========================================================================================

CREATE TABLE FORO (
    ID_FORO SERIAL PRIMARY KEY,
    ID_CLASE INT REFERENCES CLASE(ID_CLASE) ON DELETE CASCADE,
    TITULO_FORO VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TEMA_FORO (
    ID_TEMA SERIAL PRIMARY KEY,
    ID_FORO INT REFERENCES FORO(ID_FORO) ON DELETE CASCADE,
    ID_USUARIO INT REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    TITULO_TEMA VARCHAR(100) NOT NULL,
    MENSAJE_INICIAL TEXT NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ES_AVISO BOOLEAN DEFAULT FALSE
);

CREATE TABLE RESPUESTA_FORO (
    ID_RESPUESTA SERIAL PRIMARY KEY,
    ID_TEMA INT REFERENCES TEMA_FORO(ID_TEMA) ON DELETE CASCADE,
    ID_USUARIO INT REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    CONTENIDO TEXT NOT NULL,
    FECHA_RESPUESTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================================================
-- 8. GESTIÓN ADMINISTRATIVA, NOTIFICACIONES E INCIDENCIAS
-- =========================================================================================

CREATE TABLE ANUNCIO (
    ID_ANUNCIO SERIAL PRIMARY KEY,
    TITULO VARCHAR(200) NOT NULL,
    CONTENIDO TEXT NOT NULL,
    NIVEL VARCHAR(20) DEFAULT 'info' CHECK (NIVEL IN ('info', 'advertencia', 'urgente')),
    ID_AUTOR INT REFERENCES USUARIO(ID_USUARIO) ON DELETE SET NULL,
    FECHA_PUBLICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTIVO BOOLEAN DEFAULT TRUE,
    ORDEN INT DEFAULT 0,
    IMAGEN_URL VARCHAR(255)
);

CREATE TABLE INCIDENCIA_SOPORTE (
    ID_INCIDENCIA SERIAL PRIMARY KEY,
    ID_USUARIO INT REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    ASUNTO VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    ESTADO VARCHAR(20) DEFAULT 'pendiente' CHECK (ESTADO IN ('pendiente', 'resuelto')),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE NOTIFICACION (
    ID_NOTIFICACION SERIAL PRIMARY KEY,
    ID_USUARIO_DESTINO INT REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    TITULO VARCHAR(200) NOT NULL,
    MENSAJE TEXT NOT NULL,
    LEIDA BOOLEAN DEFAULT FALSE,
    ENLACE_OPCIONAL VARCHAR(255),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE BITACORA_ADMIN (
    ID_BITACORA SERIAL PRIMARY KEY,
    ID_USUARIO INT REFERENCES USUARIO(ID_USUARIO) ON DELETE SET NULL,
    ACCION VARCHAR(255) NOT NULL,
    DETALLE TEXT,
    ESTADO VARCHAR(50),
    BADGE VARCHAR(50),
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================================================
-- FIN DEL SCRIPT
-- =========================================================================================
